import type { CapacitorConfig } from '@capacitor/cli'

// CareerXP — Capacitor configuration.
//
// This file is hand-written, not generated by `npx cap init`, because the
// environment that produced this delivery has no npm registry access and
// could not install @capacitor/cli to run that command. The shape below
// matches what `cap init` would have produced; running `npx cap init`
// again locally is unnecessary and would just overwrite this with the
// same structure (answer the same values below if it prompts).
//
// appId: reverse-DNS bundle/application identifier used as BOTH the iOS
// bundle ID and the Android applicationId. "com.careerxp.app" is a
// placeholder — replace it with your organization's real registered
// identifier before any TestFlight/Play Console upload. Updated here (from
// the old com.kastro.app) while it's still safe to do so: no `npx cap add
// ios`/`android` has been run yet in this repo, so there's no generated
// native project with the old ID baked into it to migrate. Once a native
// project IS generated, changing appId again means re-running `cap add`
// from scratch (or manually renaming through Xcode/Android Studio) — get
// it right before that first `cap add`, not after.
const config: CapacitorConfig = {
  appId: 'com.careerxp.app',
  appName: 'CareerXP',
  webDir: 'dist',
  // Matches manifest.webmanifest's "orientation": "portrait" — the whole
  // UI is built as a fixed-width single-column "phone card" (see
  // .app-shell in src/index.css) and has never been tested or designed
  // for a rotated/landscape layout.
  backgroundColor: '#03030f',
  ios: {
    contentInset: 'automatic',
    // CareerXP's own header/bottom-nav chrome already reads env(safe-area-inset-*)
    // in CSS (see src/components/TopBar.tsx and .bottom-nav in index.css),
    // so let content run edge-to-edge under the status bar/notch rather
    // than having Capacitor reserve additional native space on top of that.
    scrollEnabled: true,
  },
  android: {
    // Same reasoning as iOS above — safe areas are handled in CSS.
    allowMixedContent: false,
  },
  plugins: {
    // Keep the native splash on-screen slightly past first paint so the
    // handoff to the app's own SplashScreen.tsx (which fades in the
    // CareerXP wordmark) never shows a raw white/black flash in between.
    // Duration is intentionally short — this is a bridge, not a
    // replacement for the in-app splash component.
    SplashScreen: {
      launchShowDuration: 400,
      backgroundColor: '#03030f',
      androidSplashResourceName: 'splash',
      showSpinner: false,
    },
    // Matches apple-mobile-web-app-status-bar-style="black-translucent"
    // already set in index.html for the PWA/Safari case.
    StatusBar: {
      style: 'DARK',
      backgroundColor: '#03030f',
    },
  },
}

export default config
