import { LUDO_START_OFFSETS, LUDO_RING_LENGTH, LUDO_HOME_STRETCH } from './engine'

/**
 * Pure pixel-geometry helpers for rendering the Ludo board. Deliberately
 * separate from engine.ts — the engine knows nothing about pixels, and this
 * file knows nothing about game rules. Swapping in a different board skin
 * later only touches this file and LudoBoard's render, never the rules
 * engine, the AI, or the generic framework underneath them.
 *
 * BOARD MODEL — authentic classic Ludo layout
 * ────────────────────────────────────────────
 * The board is a real 15×15 grid, exactly like a physical Ludo board:
 *
 *   ┌──────┬───┬──────┐
 *   │ base │ N │ base │   rows 0-5:  bases (0,0) and (0,9), arm cols 6-8
 *   │ (R)  │   │ (G)  │
 *   ├───┬──┴┬──┴┬──┬──┤   rows 6-8:  the cross's horizontal arm (all cols)
 *   │ W │   │ ⛝ │   │ E │            + the two vertical arms' middle band
 *   ├───┴──┬┴──┬┴──────┤
 *   │ base │ S │ base │   rows 9-14: bases (9,0) and (9,9), arm cols 6-8
 *   │ (B)  │   │ (Y)  │
 *   └──────┴───┴──────┘
 *
 * Each of the 4 "arms" (the cross's top/right/bottom/left bands) is a
 * 3-cell-wide × 6-cell-long strip. Its two OUTER lanes belong to the shared
 * 52-cell ring track; its MIDDLE lane is one seat's private 6-cell home
 * stretch, terminating in the 3×3 center square. Seat 0 (Red)'s 13-cell
 * quarter of the ring plus its home stretch are hand-authored below; the
 * other 3 seats' geometry is derived by rotating Red's 90° at a time around
 * the board's exact center — the same trick a physical board's 4-fold
 * rotational symmetry uses, so all four quadrants are guaranteed consistent
 * by construction rather than by four independently-typed coordinate lists.
 */

export const GRID_SIZE = 15
export const CELL = 40
export const BOARD_VIEWBOX = GRID_SIZE * CELL // 600
export const CENTER = { x: BOARD_VIEWBOX / 2, y: BOARD_VIEWBOX / 2 }

export const SEAT_COLORS = ['#ff4757', '#2ed573', '#f9ca24', '#3b82f6']
export const SEAT_COLORS_DARK = ['#c0392b', '#1e8449', '#c9950c', '#1d4ed8']
export const SEAT_LABELS_EN = ['Red', 'Green', 'Yellow', 'Blue']
export const SEAT_LABELS_AR = ['أحمر', 'أخضر', 'أصفر', 'أزرق']

type Cell = readonly [row: number, col: number]

function cellToPixel([row, col]: Cell): { x: number; y: number } {
  return { x: (col + 0.5) * CELL, y: (row + 0.5) * CELL }
}

/** 90° clockwise rotation of a grid cell around the board's exact center (row 7, col 7). */
function rotate90([row, col]: Cell): Cell {
  return [col, GRID_SIZE - 1 - row]
}

function rotateN(cell: Cell, times: number): Cell {
  let c = cell
  for (let i = 0; i < times; i++) c = rotate90(c)
  return c
}

// Red (seat 0)'s 13-cell quarter of the shared ring, hand-authored once:
// out of its base along the arm's top outer lane, up the left arm's inner
// column, then across the top arm's outer row to the hand-off point where
// Green's quarter begins.
const RED_RING_QUARTER: Cell[] = [
  [6, 1], [6, 2], [6, 3], [6, 4], [6, 5],
  [5, 6], [4, 6], [3, 6], [2, 6], [1, 6], [0, 6],
  [0, 7], [0, 8],
]

// Red's private 6-cell home stretch (pathPos 51..56): straight across the
// left arm's middle lane into the center square.
const RED_HOME_STRETCH: Cell[] = [
  [7, 1], [7, 2], [7, 3], [7, 4], [7, 5], [7, 6],
]

if (RED_RING_QUARTER.length * 4 !== LUDO_RING_LENGTH) {
  throw new Error('geometry/engine mismatch: ring quarter length')
}
if (RED_HOME_STRETCH.length !== LUDO_HOME_STRETCH) {
  throw new Error('geometry/engine mismatch: home stretch length')
}

/** All 52 shared ring cells, in engine path order, generated by rotating Red's quarter. */
const RING_CELLS: Cell[] = Array.from({ length: LUDO_RING_LENGTH }, (_, i) => {
  const quarter = Math.floor(i / RED_RING_QUARTER.length)
  const within = i % RED_RING_QUARTER.length
  return rotateN(RED_RING_QUARTER[within], quarter)
})

/** Each seat's 6 private home-stretch cells, generated by rotating Red's. */
const HOME_STRETCH_CELLS: Cell[][] = [0, 1, 2, 3].map((seatIndex) =>
  RED_HOME_STRETCH.map((cell) => rotateN(cell, seatIndex)),
)

/** Each seat's 6×6 base (yard) footprint, in grid cells. */
const BASE_ORIGIN: Cell[] = [[0, 0], [0, 9], [9, 9], [9, 0]]
const BASE_SIZE = 6

export function baseGridRect(seatIndex: number): { row: number; col: number; size: number } {
  const [row, col] = BASE_ORIGIN[seatIndex]
  return { row, col, size: BASE_SIZE }
}

/** Pixel rect for a seat's colored base square — used for the board background layer. */
export function yardRect(seatIndex: number): { x: number; y: number; w: number; h: number } {
  const { row, col, size } = baseGridRect(seatIndex)
  return { x: col * CELL, y: row * CELL, w: size * CELL, h: size * CELL }
}

/** One of the 52 shared ring cells' pixel center, by path index. */
export function ringPoint(index: number): { x: number; y: number } {
  const i = ((index % LUDO_RING_LENGTH) + LUDO_RING_LENGTH) % LUDO_RING_LENGTH
  return cellToPixel(RING_CELLS[i])
}

/** A seat's home-stretch cell pixel center, by pathPos (51..56 → stretchIndex 0..5). */
export function homeStretchPoint(seatIndex: number, stretchIndex: number): { x: number; y: number } {
  const clamped = Math.max(0, Math.min(LUDO_HOME_STRETCH - 1, stretchIndex))
  return cellToPixel(HOME_STRETCH_CELLS[seatIndex][clamped])
}

/** Screen position for a piece given its pathPos (-1 base, 0..50 ring, 51..56 home stretch/finished). */
export function piecePixelPosition(seatIndex: number, pieceIndex: number, pathPos: number): { x: number; y: number } {
  if (pathPos === -1) return baseSlot(seatIndex, pieceIndex)
  if (pathPos <= 50) {
    const globalCell = (LUDO_START_OFFSETS[seatIndex] + pathPos) % LUDO_RING_LENGTH
    return ringPoint(globalCell)
  }
  const stretchIndex = Math.min(pathPos - 51, LUDO_HOME_STRETCH - 1)
  return homeStretchPoint(seatIndex, stretchIndex)
}

function baseSlot(seatIndex: number, pieceIndex: number): { x: number; y: number } {
  const rect = yardRect(seatIndex)
  const inset = rect.w * 0.16
  const inner = rect.w - inset * 2
  const col = pieceIndex % 2
  const row = Math.floor(pieceIndex / 2)
  const slot = inner / 2
  return {
    x: rect.x + inset + slot * (col + 0.5),
    y: rect.y + inset + slot * (row + 0.5),
  }
}

// ── Board-background rendering data ────────────────────────────────────

export interface PathCellInfo {
  index: number
  row: number
  col: number
  x: number
  y: number
  seatIndex: number // which seat this cell's arm-quarter "belongs" to (for subtle tinting)
  isSafe: boolean
  isEntry: boolean
}

/** All 52 ring cells with render metadata (safe/entry flags come from the engine's own SAFE_CELLS via the isSafe/isEntry callbacks passed in). */
export function pathCells(isSafeFn: (i: number) => boolean, entryOffsets: number[]): PathCellInfo[] {
  return RING_CELLS.map(([row, col], index) => {
    const { x, y } = cellToPixel([row, col])
    const seatIndex = Math.floor(index / (LUDO_RING_LENGTH / 4))
    return {
      index, row, col, x, y, seatIndex,
      isSafe: isSafeFn(index),
      isEntry: entryOffsets.includes(index),
    }
  })
}

export interface HomeStretchCellInfo {
  seatIndex: number
  stretchIndex: number
  row: number
  col: number
  x: number
  y: number
  isFinishCell: boolean
}

/** All 24 home-stretch cells (6 per seat) with render metadata. */
export function homeStretchCells(): HomeStretchCellInfo[] {
  const out: HomeStretchCellInfo[] = []
  for (let seatIndex = 0; seatIndex < 4; seatIndex++) {
    HOME_STRETCH_CELLS[seatIndex].forEach(([row, col], stretchIndex) => {
      const { x, y } = cellToPixel([row, col])
      out.push({ seatIndex, stretchIndex, row, col, x, y, isFinishCell: stretchIndex === LUDO_HOME_STRETCH - 1 })
    })
  }
  return out
}

/** The 4 triangular wedges of the center "home" square, one per seat, meeting at the exact board center — the classic pinwheel graphic. */
export function centerTriangles(): { seatIndex: number; points: string }[] {
  const c = 6 * CELL // inner edge of the 3×3 center square
  const f = 9 * CELL // outer edge
  const mid = { x: CENTER.x, y: CENTER.y }
  const tl = { x: c, y: c }
  const tr = { x: f, y: c }
  const br = { x: f, y: f }
  const bl = { x: c, y: f }
  const poly = (...pts: { x: number; y: number }[]) => pts.map((p) => `${p.x},${p.y}`).join(' ')
  return [
    { seatIndex: 0, points: poly(bl, tl, mid) }, // left wedge → Red (home stretch enters from the left arm)
    { seatIndex: 1, points: poly(tl, tr, mid) }, // top wedge → Green
    { seatIndex: 2, points: poly(tr, br, mid) }, // right wedge → Yellow
    { seatIndex: 3, points: poly(br, bl, mid) }, // bottom wedge → Blue
  ]
}

export function cellRect(row: number, col: number, w = 1, h = 1) {
  return { x: col * CELL, y: row * CELL, w: w * CELL, h: h * CELL }
}
